### ISSUE TITLE
[3.0][improvement] better mailing handling

### ISSUE THREAD

**Issue by caprycorne** [panique/php-login#441]
Hello buddies,
Just wanted to share my implementation of mail sending inside php-login. 
Before you start screaming at me for not to focus on the login system (hope you won't!), It may be useful for people who wants to add HTML/Images in their mails. Nowadays, every website or almost have a logo. It could even be a condition for a client.
On that purpose, I wrote a class extending PHPMailer who let you specify a HTML template (inside a directory of your choice, represented by a const), add vars to this HTML templates and auto_embedding images in the mail.
Extending PHPMailer's class have even another advantage: all the SMTP check is handled in the constructor, making your models a little more thin.

I don't know if some of you are interested in this 'feature', if I can call it a feature but I would be happy to share it.
I used it for the request_password_reset mail, and this is what my Model method look like atm:

    public function sendPasswordResetMail($user_name, $user_password_reset_hash, $user_email)
    {
        // create our Mailer (extending PHPMailer) object here
        $mail = new Mailer;
        // create link for user's password reset hash and pass it to the template 'password_reset.html'
        $link = EMAIL_PASSWORD_RESET_URL . '/' . urlencode($user_name) . '/' . urlencode($user_password_reset_hash);
        $pVars = array('%user_name%' => $user_name,
                       '%user_password_reset_link%' => $link);
        $mail->buildMail('PASSWORD_RESET', $user_email, $pVars);
        // send the mail
        if($mail->Send()) {
            $_SESSION["feedback_positive"][] = FEEDBACK_PASSWORD_RESET_MAIL_SENDING_SUCCESSFUL;
            return true;
        } else {
            $_SESSION["feedback_negative"][] = FEEDBACK_PASSWORD_RESET_MAIL_SENDING_ERROR . $mail->ErrorInfo;
            return false;
        }
    }

And if someone need the complete implementation (Mailer.class, some changes in config.php and 2 folders created to store mail templates / mail images), don't hesitate to contact me.
Thank you for reading!

**Comment by panique** [comment]
I've just added something like this, have a look on this ticket for more info and detailed code: https://github.com/panique/php-login/issues/501
