### ISSUE TITLE
[2.0][improvement] page rendered after login with cookie

### ISSUE THREAD

**Issue by VD17593** [panique/php-login#442]
I've done a little searching for the problem I encountered last friday.
With the use of the Zend Eclipse debugger (which is a great tool, thanks for the hint), I found a solution which I will apply on my branch of your application. 
I'm sharing it, perhaps there's an inspiration or enhancement.

I found that when session expires, and login with cookie is launched, the application renders by default a page (set to dashboard/index). When working with the appliction, I found it annoying that, when for example a user clicked on My Notes, he was rederected to another page, even if normally he should be able to consider himself still logged in through the remeber me cookie.

So how I solved.
First I swiched the authentification and the parent::__construct form place.
Authentification, after session expiration, will redirect by default to the login page. Putting the controller construct after it, permits to override it by the 'login/loginWithCookie', if a cookie exists. 
(I hope there is no contra indication for these being switched)

     class Note extends Controller {
    /**
     * Construct this object by extending the basic Controller class
     */   
     public function __construct()    {
        // VERY IMPORTANT: All controllers/areas that should only be usable by logged-in users
        // need this line! Otherwise not-logged in users could do actions. If all of your pages should only
        // be usable by logged-in users: Put this line into libs/Controller->__construct
        Auth::handleLogin();     
        parent::__construct();
    }

Then, in the controller constructer, I give the variables in the header:

     class Controller {
     function __construct()     {
        Session::init();
        // user has remember-me-cookie ? then try to login with cookie ("remember me" feature)
        if (!isset($_SESSION['user_logged_in']) && isset($_COOKIE['rememberme'])) {
            header('location: ' . URL . 'login/loginWithCookie/' . $_GET['url']);
        }

Finally in login I capture the variables to render the page asked

     function loginWithCookie($x,$y)     {
       $login_model = $this->loadModel('Login');
        $login_successful = $login_model->loginWithCookie();
        if ($login_successful) {
        	//header('location: ' . URL . 'dashboard/index');
            header('location: ' . URL . $x . '/' . $y);
        } else {
            // delete the invalid cookie to prevent infinite login loops
            $login_model->deleteCookie();
            header('location: ' . URL . 'login/index');
        }
    }

I've tried it, and it seems to work.

**Comment by panique** [comment]
@VD17593 He, not sure what you mean by this.

Your last part (performance suggestion) is unclear for me, as this code is not run after Auth::handleLogin exit()'ed the application.

The time-out/remeber-me part is also unclear, as this cannot happen: Before every action Auth:handleLogin is called and there're only 2 possibilities: user is not logged in (anymore), then app is closed with exit(), or user is logged in, then aciton is performed.

I'll close this ticket for now, feel free to re-open is something changes or I'm wrong!

see this please: https://github.com/panique/php-login/blob/master/application/libs/Auth.php#L22
