### ISSUE TITLE
[2.0][major bug] Facebook removed / renamed API 3.0 SDK

### ISSUE THREAD

**Issue by nyubbie** [panique/php-login#520]
Did the files just get moved?

I realise there is one at: https://github.com/facebookarchive/facebook-php-sdk

and a newer version at: https://github.com/facebook/facebook-php-sdk-v4

Just FYI... not sure if its a real issue.

**Comment by panique** [comment]
I've removed Facebook completely from develop branch for now, let's reimplement it later maybe (via native SDK or via OAuth2)
