### ISSUE TITLE
[2.1][question] Should we directly access $_POST['x'] etc. or encapsulate, like $app->post('x') ?

### ISSUE THREAD

**Issue by panique** [panique/php-login#535]
The code analysis of Codacy brought up some very interesting things, and I'm unsure about how to deal with them: https://www.codacy.com/public/panique/phplogin/issues?bid=789836&filters=W3siaWQiOiJDYXRlZ29yeSIsInZhbHVlcyI6WyJDb2RlIFN0eWxlIl19XQ==

**Comment by panique** [comment]
done in develop

**Comment by atdotslashdot** [comment]
I'm struggling to catch up with the Christmas rush :-)
can you point to the commit, I can't spot it here....
https://github.com/panique/php-login/commits/develop

**Comment by panique** [comment]
This is a all-over-the-project change, a changed this step by step. So no dedicated commit, sorry. But it's basically just $_POST excahnged by Request::post everywhere plus the new Request class.
