### ISSUE TITLE
[2.1] Model loading

### ISSUE THREAD

**Issue by M0ritzWeide** [panique/php-login#545]
Hey,
because i have a lot of models and i dont want to load all of them in every Controller i think a function for loading one model (like theprevious Version) is still better :)

**Comment by Dominic28** [comment]
Same here.
Think about a situation where you need lots of models when the user logged in (or in special areas), but not for logged out users.

**Comment by panique** [comment]
Any ideas how to do this ?

**Comment by M0ritzWeide** [comment]
Of Course Option 4 is awesome but the Framework is not Zend or anything else so i think Option 2 is good enough for the Fraework :)

**Comment by panique** [comment]
@M0ritzWeide Damn good point! :)

**Comment by panique** [comment]
@M0ritzWeide The new 2.1 does this the following way: Nothing is autoloaded, but every model method is a static method, so you can use every model method everywhere without any dependencies or without having to load anything.

A simple example, from inside a controller or inside another model (!):

```php
$user_id = UserModel::getUserNameByUserId(17);
```

This will simply put the user #17's username into $user_id. Regardless where you use it, this static method will fetch a database connection automatically (and other methods will use the same connection too), all it needs is the id.

There are for sure better ways to do this, but i like this way.
