### ISSUE TITLE
[legal] How to stop trolls from selling this script 1:1 ?

### ISSUE THREAD

**Issue by panique** [panique/php-login#546]
This script is licenced under MIT, so it can be used for free in any project, regardless if it's commercial or not. You can for sure also build something with it and sell it for lots of money. That's intented and the idea behind the script / licence.

But, what really really pissed me off are people who take this script, remove the copyright / licence information, the readme and then sell it, right as it is, on certain script selling marketplaces.

This is - from a legal perspective - a hard edge case, and from moral perspective it's completely wrong. This is like selling jQuery (custom, formerly MIT) or Wordpress (GNU) itself.

Surprisingly some free-software activists may say: "That's their right, that's the consequence of publishing open-source!", but I don't agree with that. It's wrong, as **it's clearly scam**.

### My questions here

1. How can we prevent people from selling the script 1:1 on script marketplaces while still making it as free and open-source as possible ? Meaning: Which licence would fit best here ?
2. If you have more information on that topic, please share it, especially links.
3. Is this simply a consequence that open-source has to deal with, as it's not directly forbidden to sell 1:1 copies ?

**Comment by Codexing** [comment]
Might not be a lot of help but it's pretty easy to report these cases to places such as Envato (who are usually pretty good from experience) and they are removed quite timely. Usually results in a ban too.

I think MIT allows it to be sold doesn't it? Same with GNU. Refer here: https://www.gnu.org/philosophy/selling.html  "So if you are redistributing copies of free software, you might as well charge a substantial fee and make some money."

Pretty much every FSF approved license allows selling of source code. Unfortunately I am not sure anything can really be done except for complaining to the marketplaces (where the practice is usually against their policies).

However, one exception which I think could be fitting to your idea is the Mozilla Public License. From what I can tell it only allows people to sell a modified version, if the source code remains original it must be offered for free. "The MPL allows covered source code to be mixed with other files under a different, even proprietary license. However, code files licensed under the MPL must remain under the MPL and freely available in source form." (From Wikipedia). From my understanding this means that any unmodified code must remain free.

Not 100% sure on how it all fits together, though. I'll keep reading.
