### ISSUE TITLE
[2.1] Static model methods: Yes or No ?

### ISSUE THREAD

**Issue by panique** [panique/php-login#548]
Performing a method inside a model-class is usually made like this in the 2.0 version of php-login:
````php
// initialize the instance of the model class
// the constructor of LoginModel will automatically fetch the db connection
$LoginModel = new LoginModel();
$LoginModel->doThis();
$LoginModel->doSomethingElse();
```

This is annoying as you'll have to write the `new LoginModel();` part when you want to do something. In theory it would be easier to use static methods all around like:

```php
LoginModel::doThis();
```
No need to initialize anything first! You could also do this inside another model class! But, and that's the problem, every static method needs the database connection, and a constructor doesn't work with static methods for sure, so you'll have to get the db connection every time in every model class.
This seems also totally wrong. Also, static methods are usually "bad code" and harder to test afaik.

Any opinions, ideas and maybe code on that issue ?

**Comment by M0ritzWeide** [comment]
Static methods are quite sexy because you dont have to initialize anything but you say it you need the DB Connection and then you have to give it about the parameter and this means you need the DB Connection in every Controller. So maybe you can make the DB Connection in the Construct from the Controller? 
And a Pro for the normal functions is that you dont have to include all Models :)

**Comment by panique** [comment]
FYI gentlemen: I'm currently changing all model methods to static methods. This might look like a step backwards (and maybe it even is), but removes the need to load the model class manually (or having an overdozed autoloader loading all model classes, even if not needed). Now it's possible to do every model method basically everywhere, even inside other model methods :)

That's the killer feature for me, being able to do `userModel::getUserNameByUserId(17)` inside any other method/function/view makes this super-intuitive and removes struggling around. There're probably better ways to do this, but as someone here on GitHub said: This is not Zend Framework, so we shouldn't care too much :)

**Comment by panique** [comment]
The current version 2.1 in develop branch does everything with static methods. This might be a step backwards from architecture point of view, but it does also allow very easy usage of model methods. Every model class can use every other model class/method with one line of code. Every model method is (or better: will be) a tiny unit that does not rely on anything else, method requests everything it needs from the argument list (like xxx($param1, $param2)) or inside the method itself (like the database connection).

This is just a very first draft, everything might change!!
