### ISSUE TITLE
[2.1][security] Handle raw user input or only stripped / cleaned ?

### ISSUE THREAD

**Issue by M0ritzWeide** [panique/php-login#550]
Hey,
I look at you new updates and i saw the Request class. I think this is a good idea but acces to the Superglobal without any functions like htmlentities() or strip_tags() so i think when you do this http://pastebin.com/pacfnkNU the Request class is safe and when anyone need HTML Tags in a Superglobal he can take $_POST or $_GET.

**Comment by panique** [comment]
Hey Moritz,

I understand your point, but these days with PDO it's not necessary to strip your content. This gets tricky when you REALLY want to save code into the database.

My idea (maybe totally wrong): We could echo out only cleaned vars in the view, to the render() method cleans all input ? A little bit messy as the view itself should not manipulate data, but that's how the template engines Twig / Smarty also do this.

**Comment by M0ritzWeide** [comment]
Or a funtion like Request::safePost() and Request::post() :)

**Comment by panique** [comment]
!!! or :: post() [cleaned] and ::rawPost [untouched]. How do other frameworks do this ?

**Comment by M0ritzWeide** [comment]
I dont know but this is also possible :D

**Comment by slaveek** [comment]
I'm not sure that Request class is a good place for clean, sanitize, validate data. Maybe better is something like Validate class as separate tool with the methods like:
* isString($string)
* isEmail($email)
* isPassword($password)
* isCleanHtml($html)

In future easy to extend
* isDate
* isCity
* isCountry
* etc etc

Use some regex or core PHP functions in the methods to clean, sanitize, validate data.

**Comment by Dominic28** [comment]
I think a validation class would be too much for php-login. Some of slaveek's examples are one-liners anyways. But post() and rawPost() sounds fine for me :)

**Comment by Dominic28** [comment]
Another solution could be to give an optional bool to the method, which would look something like this:

```
public static function post($key, $clean = NULL)
{
    if (isset($_POST[$key])) {
        return isset($clean) ? trim(strip_tags($_POST[$key])) : $_POST[$key];
    }
}
```

Trim and strip_tags is just an example of course :)

**Comment by M0ritzWeide** [comment]
Awesome Idea Dominic :)

**Comment by panique** [comment]
@Dominic28 @M0ritzWeide This is really clever and beautiful! :) Love it!

**Comment by panique** [comment]
btw this here is afaik the most secure and most correct way to echo out content in a view. Not sure exactly why, but that's the consequence of long discussions in other projects. Let's investigate this a little bit. Maybe a look into other frameworks is useful.

```php
<?php echo htmlspecialchars($var, ENT_QUOTES, 'UTF-8'); ?>
```

**Comment by slaveek** [comment]
@Dominic28 it's very good idea indeed. What about to set `$clean` to `false` by default instead of `null` and then
```php
return ($clean) ? trim(strip_tags($_POST[$key])) : $_POST[$key];
```
It actually doesn't change anything but if you read the code, I think is nicer if 

clean is true or false
than
clean is empty or null

@panique I think that  to echo out the content htmlspecialchars() is more flexible and it have reverse htmlspecialchars_decode() function. So, htmlspecialchars encoded data can be store in variable or in data base and then simply decoded and finally strip from tags if needed.

**Comment by Dominic28** [comment]
@slaveek  Yes this saves us the isset(), so it's okay for me :)

**Comment by panique** [comment]
Done in develop branch!
https://github.com/panique/php-login/commit/01ac28ef8626a6cfea25cc33e1e6711d8753bd95

I've not done this for GET/cookie etc., unsure if this is necessary and useful (?)
