### ISSUE TITLE
[2.1][code quality] PSR-2 Method visibility

### ISSUE THREAD

**Issue by slaveek** [panique/php-login#551]
Hi,
I found that all class methods in all controllers have not visibility defined.
It's not a bad thing. We can find in [PHP Manual](http://php.net/manual/en/language.oop5.visibility.php) that:

> Class methods may be defined as public, private, or protected. Methods declared without any explicit visibility keyword are defined as public.

However it doesn't fit to PSR-2 coding standards.
https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md#43-methods

**Comment by panique** [comment]
Thanks, good point! Fixed in develop branch.
