### ISSUE TITLE
[2.0] echo url_paramater

### ISSUE THREAD

**Issue by User99un27** [panique/php-login#552]
Hey,
How can I echo $url_paramater if it's set? For example, I have URL like this: www.domain.com/login/register/url_paramater and I want to echo url_paramater in that same register page. Is that possible?

**Comment by panique** [comment]
Hi, you could do this:

1. In https://github.com/panique/php-login/blob/master/application/libs/Application.php, write a method that gives back the controller name / action name, like getControllerName().

2. In the View (https://github.com/panique/php-login/blob/master/application/libs/View.php) write a method that uses this above method, like getControllerName()

3. Or look at this method https://github.com/panique/php-login/blob/master/application/libs/View.php#L50, it does nearly this. It would be one line of code to write.
