### ISSUE TITLE
Chapta Does not generate

### ISSUE THREAD

**Issue by martijnmelchers** [panique/php-login#553]
Hi, i need help with my  PHP-Login professional, it says: The file Gregwar\Captcha\CaptchaBuilder.php is missing in the libs folder. But if you go to: http://beta.martijnmelchers.nl/private/php-login/application/libs/Gregwar/Captcha/ its there!How do i fix this error!?

**Comment by M0ritzWeide** [comment]
You have to follow the instruction and then everything works :D

**Comment by martijnmelchers** [comment]
Which Introductions, where!?

**Comment by martijnmelchers** [comment]
@M0ritzWeide

**Comment by panique** [comment]
@martijnmelchers C'mon, seriously ?
1. This is not a support forum here, it's a bug / feature list
2. Follow the install tutorial, like everybody else
3. Read the readme, like everybody else.
4. When you are seriously asking "Which Introductions, where!?", then you might not have the minimum intellect to use this script. Seriously. There's an install tutorial right here on GitHub, impossible to miss. There are links to 2+ another tutorials. There links and tutorials for every little step. There's a list of minimum requirements and a paragraph that clearly says that this is not for beginner and people who have absolutly no idea what Composer is and how to use.

So, please don't put your "I have not read the install tutorial and not read the readme but please help me" comments here. I don't want to be mean, but when you spend 1000s of hours of developing this and writing detailed tutorials and everything and then people are still not clever enough to use it, well, then things get frustrating.

**Comment by martijnmelchers** [comment]
I read the intructions. 10 times. over and over. cant find it.

**Comment by panique** [comment]
No, you definitly did not. I'm also 100% sure you have never worked with Composer or any other PHP application before. No offending, just saying. Even if you are doing this for the very first time, then the tutorial will guide you through the process easily. You still messed it up. From the URL alone (!) I can clearly see you have not read the tutorial(s) and you have also done stuff that has nothing to do with the tutorial. This makes absolutly no sense.

Please don't use this script, you obviously have no idea what you are doing, this will only bring you into a lot of problems! Hire a developer to do the job.

**Comment by martijnmelchers** [comment]
But everything works, except chapta just help me?

**Comment by martijnmelchers** [comment]
<h1>Just help me :( Im only 14 i don't have money to hire developers!?</h1>

**Comment by M0ritzWeide** [comment]
Im 14 too and i think i can handle the script from @panique  good (good for my needs :D). I learn PHP for a few years so you have to spend enough time to teach the Language yourself than you dont have to hire a Developer. ;)

**Comment by panique** [comment]
@M0ritzWeide He Moritz, are you really 14 ? :) Wow! If you would say you are 27 i would totally believe you too :)

**Comment by M0ritzWeide** [comment]
Haha @panique
