### ISSUE TITLE
[2.1][Question] Is there a good PHP image handling lib ? Avatar handling should move out of the main project

### ISSUE THREAD

**Issue by panique** [panique/php-login#555]
As the avatar handling (uploading, resizing, cropping, converting etc.) is not really part of the login process it totally makes sense to outsource this to a library that does this better than my crappy approach :)

Any suggestions ?

**Comment by panique** [comment]
Looks superhot: https://github.com/Gregwar/Image

**Comment by slaveek** [comment]
I really like this: https://github.com/claviska/SimpleImage

**Comment by Codexing** [comment]
Forgive me in advance for going against the grain. I understand the desire to outsource though I think there is still a good argument for it to remain native. Your current code works well and is clean and minimal. The functionality required by the script is pretty small -- I mean really there's upload, resize, move perhaps, and delete. In my opinion the use of a pre-made library would be unneeded bloat and excessive given that only core functions are required. I also notice both of these suggestions, as well as 2.0 of php-login, use GD. I've worked with that and ImageMagick and I have to say ImageMagick makes GD entirely redundant in terms of image quality and functionality. 

It also has the functionality as similarly described in the linked projects by default. I.e: http://php.net/manual/en/class.imagick.php -- resizeImage(), removeImage(), etc. From what I know it has good image validation too. But, I'd be happy to convert my own code to use ImageMagick, it may be a bit too "progressive" to require it for this project, kind of like requiring nginx. I know that it's commonly installed on most servers (shared hosting, etc.) but I am unaware of any statistics. See here as an example of quality difference. It's a dated article but still relevant: https://foliovision.com/2010/03/imagemagick-vs-gd

IIRC the core difference is that GD does not retain the embedded color profile in the image when processing is applied whereas Imagick does. I guess my argument concludes that if we can require developers to install another library or class for avatar functions, we can require them to install ImageMagick which is a PECL install. If you're thinking we're only using it for avatars here and the quality isn't highly important I think we need to revisit that thought. As mobile usage and high DPI monitors become more prevalent the size and detail requirements of avatars will grow with it. Small images are quickly becoming a thing of the past.

Also remember: ImageMagick has a very high level of adaption. Most open source applications use it (phpBB, vBulletin, XenForo, WordPress has popular plugin for it, for example) as well as apparently being used by some pretty massive websites <3

**Comment by panique** [comment]
@Codexing Good point, thanks! Maybe we can put the avatar-stuff inside an own class and make it extremely small, without options etc., so that it's enough for a nice live-demo, but nothing more.

Btw I really didn't know that PHP can handle all this so well nativly! Excellent!

**Comment by Codexing** [comment]
@panique no problems! The minimalist avatar class would be a fantastic idea in my opinion. Would also make it easy for modifying where people wish to expand it based on their own needs.

**Comment by panique** [comment]
Done in develop branch! For simplicity the current version 2.1 (develop branch) does this as simple as possible and only uses native PHP functions.
