### ISSUE TITLE
[2.1+][question] Going SSL / HTTPS: Who has lots of experience ?

### ISSUE THREAD

**Issue by panique** [panique/php-login#556]
Hi followers,

upcoming versions of php-login should definitly increase security by allowing easy usage of HTTPS.
My experiences with https are very low, and I don't want to do this by myself, so I'm asking:

Can somebody who has much more experience with this give a short summary what to do, if code-changes are necessary, what specials situations might occur, how the most simply implementation might look like (pseudocode), etc.

Thanks!

**Comment by M0ritzWeide** [comment]
I think you dont have to do anything it is only Server Sided. I dont use a Certificate before but i think only Server Side :)

**Comment by sopitz** [comment]
Indeed. You only change your web server's settings and SSL is in place.
Besides that, some changes within the .htaccess might be useful as most people don't have wildcard ssl certs and probably want to make sure that www.* calls and * calls get redirected to the corresponding domain encrypted with ssl. Let me see if I can give some examples later.

**Comment by CaptainKarma** [comment]
If you don't want to use .htaccess, you can use this simple PHP code at the top of each page to force redirection to https;

if($_SERVER["HTTPS"] != "on")
{
    header("Location: https://" . $_SERVER["HTTP_HOST"] . $_SERVER["REQUEST_URI"]);
    exit();
}

**Comment by Codexing** [comment]
@panique nice forethought. I've used HTTPS for all my projects completed in the past few years. From memory I've never had to adjust any PHP code unless there is a redirect of some sort. The only code changes I've had to make are to the HTML and CSS to use protocol relative URLs. For example where jQuery or Bootsrap is loaded from a CDN, I use protocol relative URLs. I've always redirected to HTTPS at the webserver level.

Which brings me to another point which you're probably sick of me going on about. HTTPS is what made me move away from Apache to nginx. SPDY is now supported on Apache with enough fiddling however it has native support by nginx. This is actually a big deal. If you've ever used HTTPS with highly dynamic and feature rich websites, SPDY can literally make your website multitudes faster. In fact, in some scenarios it can make HTTPS faster than HTTP given the ability to load everything at once... It's the real deal, see even this Apache benchmark: http://www.neotys.com/blog/performance-of-spdy-enabled-web-servers/

All browsers support SPDY, all major websites use SPDY. Facebook, Twitter, Google (every Google powered website) among just about any top 1,000 Alexa HTTPS website uses SPDY and is likely using nginx (http://w3techs.com/technologies/segmentation/ce-spdy/web_server). Nginx has some amazing SSL optimizations included within.

My point is that perhaps php-login should consider nginx as a primary platform, but don't worry I'll continue to love it either way :+1:

**Comment by panique** [comment]
@Codexing Excellent! Super-exciting stuff! I think php-login should ship with default configs for BOTH: apache and nginx :) Do you know if SPDY affects the code in any way or is this purely server config stuff ?

I've absolutly no experience with this.

**Comment by Codexing** [comment]
@panique Sounds like an excellent plan with both config's! And no code changes required at all, it's all server side :)

**Comment by tankerkiller125** [comment]
@panique SPDY will not effect PHP in anyway its more of an async loader for CSS and JS. Thats all it really does based on my experience with it but I may be wrong.

**Comment by Codexing** [comment]
That's true but it's also more complex than that. It's actually the working base for specifications for the draft of HTTP/2. I.e, HTTP/2, which is a multiplexing protocol is based upon SPDY. SPDY is essentially the grassroots technology which is expected to be relevant for as long as HTTP/2 takes, which could be a long considering the first draft was only a few weeks ago.

Main difference: The biggest difference between HTTP and SPDY, is that each user action in SPDY is given a "stream ID", meaning there is a single TCP channel connecting the user to the server. SPDY splits requests into either control or data, which is a “parse binary protocol with two types of "frames".[9] SPDY has shown evident improvement from HTTP, with a new page load speedup ranging from 11.81% to 47.7%.[13]

Cont: HTTP/2 uses SPDY as a jumping-off point; though SPDY is an improvement on HTTP 1.1...

http://en.wikipedia.org/wiki/HTTP/2

**Comment by panique** [comment]
Link from old HTTPS ticket: http://erik.io/blog/2013/06/08/a-basic-guide-to-when-and-how-to-deploy-https/

**Comment by panique** [comment]
Okay, thanks for the infos! :)
