### ISSUE TITLE
captcha error when registering

### ISSUE THREAD

**Issue by westcut** [panique/php-login#559]
captcha doesnt show so new accounts cannot be created and once in account cannot edit avatar

**Comment by KatzArie** [comment]
Did you followed the tutorial step by step?

`install GD (for the Captcha): sudo apt-get install php5-gd`

Gregwar's Captcha https://packagist.org/packages/gregwar/captcha

https://github.com/panique/php-login#used-packages-via-composer

https://github.com/panique/php-login#run-composer

**Comment by westcut** [comment]
yes i followed all, is there a ready version i could get? like the one on the test site

**Comment by westcut** [comment]
i wanna add some custom code, this is best i have found in all my checks

**Comment by panique** [comment]
Sorry dude, follow the install tutorial like everybody else.

**Comment by panique** [comment]
Beside that, "captcha doesnt show" is not a clever bug report. Show some infos, show what you have tried etc.

**Comment by westcut** [comment]
http://klixoft.com/sms/index/index
i got it up and running, but when registering at http://klixoft.com/sms/login/register no captcha.
i installed the other versions without problems, i had one user from the minimal version and when i added files for the professional version that user was still there so i saw what inside was like, i have honetly and been trying for hours till i even went and tried other products, i can pay or donate if need to get assistance or mayb someone could give simpler setup explanation for getting it working online

proof that i have been trying all day 
http://prntscr.com/5u76vk
http://prntscr.com/5u771i
http://prntscr.com/5u7773
http://prntscr.com/5u77es
http://prntscr.com/5u77j8
http://prntscr.com/5u77mz
http://prntscr.com/5u77qf
http://prntscr.com/5u77vq
http://prntscr.com/5u7808
http://prntscr.com/5u784e
http://prntscr.com/5u788e
http://prntscr.com/5u78df
http://prntscr.com/5u78oj

**Comment by Codexing** [comment]
The file Gregwar\Captcha\CaptchaBuilder.php is missing in the libs folder.

Have you installed the Gregwar Captcha package?

**Comment by panique** [comment]
"i had one user from the minimal version and when i added files for the professional version"

Dude, seriously, don't do this here! What you do it totally idiotic. Follow the install tutorial. Why the hell are you trying to set this up "your own way", mixing two totally different scripts and totally skipping the installation ? This is idiotic.

Again: This is a bug report list, not a personal support forum for people who are not even able to read a simple install tutorial. You have NOT read the install tutorial.

Please don'T post here again.

**Comment by westcut** [comment]
i will give up i have tried and followed all instructions, and stuck at #7 thanks for nothing, and the user thing was an accident

**Comment by panique** [comment]
@westcut Other people have written this peace of software, plus extremely detailed nearly idiot-proof tutorials, plus sub-tutorials on all the things like mod_rewrite, plus masses of comments on the entire code, spending thousands of hours of work, for free, for you. "Thanks for nothing" is wrong here, dude. Read the readme, follow the install tutorial, and simpyl dont weird, unneccessary, exotic and completely off-the-tutorial stuff, and please dont post your personal help requests inside this issue board! I cannot hear it anymore.

And seriously, you don't even get to do the composer install. Even the min. requirement list says that you should know how composer works. I'll never understand why people still do X and Y when the readme clearly says do A, B and C.

Please also note that the people on open-source project don't have nerve and time to fix your stuff, this is simply not possible.
